name: santak
channels:
  - anaconda
  - conda-forge
dependencies:
  - pyqt
  - qt
  - python=3.7
  - numpy
  - opencv
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - fonttools
  - luigi
  - tqdm
